[package]
name = "ruse"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ruse"
path = "main.rs"

[lib]
path = "lib.rs"

[dependencies]
miette = { version = "7", features = ["fancy"] }
thiserror = "1"
