[package]
name = "ruse"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ruse"
path = "src/main.rs"

[workspace]
members = [".", "crates/*"]

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
rustyline = "15.0.0"
